# -*- coding: utf-8 -*-
"""
Backtest Engine — empirical validation for the football scoring model
======================================================================

Two modes:

1. REAL-DATA backtest (``--real <path>`` or ``--supabase``)
   Evaluates the engine against matches that carry a real ``actual_result``
   ('1' / 'X' / '2'). Reports accuracy, Brier score, log-loss and flat-stake
   ROI on value bets. Use this once settled results are exported from
   Supabase (or any JSON/CSV that includes outcomes).

2. SIMULATION backtest (``--simulate N``)
   A Monte-Carlo ablation study with ground truth known by construction.
   For each trial we draw "true" home/away goal rates, generate a real
   scoreline from independent Poisson draws (→ the true 1/X/2 outcome),
   then build the noisy match row the engine actually sees (odds derived
   from the true probabilities plus bookmaker margin + noise, plus form).
   We score that row with the engine *with* and *without* the new Poisson
   draw source and compare calibration. Because draws are generated by the
   real goal process, this isolates whether the Poisson draw modelling
   improves probability calibration — especially on draws, the outcome the
   old heuristic handled worst.

Metrics
-------
- accuracy:  fraction of top-pick predictions that match the outcome
- brier:     mean squared error of the full 1/X/2 probability vector
             (lower is better; the proper score for calibration)
- log_loss:  mean negative log-likelihood of the true outcome
             (lower is better; punishes confident mistakes)
- draw_brier: Brier restricted to matches whose true outcome was a draw

Usage
-----
    python backtest_engine.py --simulate 5000
    python backtest_engine.py --simulate 5000 --seed 7
    python backtest_engine.py --real results/settled_football.json
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import sys
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from football_scoring_engine import (  # noqa: E402
    FootballScoringEngine,
    _poisson_pmf,
)


# ---------------------------------------------------------------------------
# Metrics container
# ---------------------------------------------------------------------------

@dataclass
class BacktestMetrics:
    label: str
    n: int = 0
    correct: int = 0
    brier_sum: float = 0.0
    logloss_sum: float = 0.0
    draw_n: int = 0
    draw_brier_sum: float = 0.0
    # ROI on value bets (real-data mode only)
    bets: int = 0
    pnl: float = 0.0

    def add(self, probs: Tuple[float, float, float], actual: str,
            pick: str, ev: float = 0.0, odds: float = 0.0) -> None:
        """Record one prediction.

        probs: (p_home, p_draw, p_away)
        actual: '1' | 'X' | '2'
        """
        self.n += 1
        idx = {'1': 0, 'X': 1, '2': 2}[actual]
        target = [0.0, 0.0, 0.0]
        target[idx] = 1.0

        self.brier_sum += sum((p - t) ** 2 for p, t in zip(probs, target))
        p_true = max(1e-12, min(1.0, probs[idx]))
        self.logloss_sum += -math.log(p_true)

        if pick == actual:
            self.correct += 1

        if actual == 'X':
            self.draw_n += 1
            self.draw_brier_sum += sum((p - t) ** 2 for p, t in zip(probs, target))

        # Flat-stake value-bet ROI
        if ev > 0 and odds > 1:
            self.bets += 1
            self.pnl += (odds - 1.0) if pick == actual else -1.0

    def summary(self) -> Dict[str, float]:
        n = max(1, self.n)
        return {
            'label': self.label,
            'n': self.n,
            'accuracy': round(self.correct / n, 4),
            'brier': round(self.brier_sum / n, 4),
            'log_loss': round(self.logloss_sum / n, 4),
            'draw_n': self.draw_n,
            'draw_brier': round(self.draw_brier_sum / max(1, self.draw_n), 4),
            'value_bets': self.bets,
            'roi': round(self.pnl / self.bets, 4) if self.bets else 0.0,
            'net_units': round(self.pnl, 2),
        }


# ---------------------------------------------------------------------------
# Engine variants for ablation
# ---------------------------------------------------------------------------

def _make_engine(with_poisson: bool) -> FootballScoringEngine:
    """Return an engine with the Poisson source on (default) or off.

    Disabling is done by zeroing the ``poisson`` weight, which makes the
    source contribute nothing — an exact ablation of the new draw model.
    """
    eng = FootballScoringEngine()
    if not with_poisson:
        eng.weights = dict(eng.weights)
        eng.weights['poisson'] = 0.0
    return eng


def _probs_from_scored(sm) -> Tuple[float, float, float]:
    return (sm.cal_home, sm.cal_draw, sm.cal_away)


# ---------------------------------------------------------------------------
# Simulation mode
# ---------------------------------------------------------------------------

def _true_poisson_probs(lh: float, la: float, max_goals: int = 10
                        ) -> Tuple[float, float, float]:
    """Ground-truth 1/X/2 probabilities for goal rates (lh, la)."""
    hp = [_poisson_pmf(lh, i) for i in range(max_goals + 1)]
    ap = [_poisson_pmf(la, j) for j in range(max_goals + 1)]
    ph = pd = pa = 0.0
    for i in range(max_goals + 1):
        for j in range(max_goals + 1):
            p = hp[i] * ap[j]
            if i > j:
                ph += p
            elif i == j:
                pd += p
            else:
                pa += p
    tot = ph + pd + pa
    return ph / tot, pd / tot, pa / tot


def _sample_score(lh: float, la: float, rng: random.Random) -> Tuple[int, int]:
    """Sample a real scoreline from two independent Poisson processes."""
    def _poisson_sample(lam: float) -> int:
        # Knuth's algorithm
        L = math.exp(-lam)
        k = 0
        p = 1.0
        while True:
            k += 1
            p *= rng.random()
            if p <= L:
                return k - 1
    return _poisson_sample(lh), _poisson_sample(la)


def _form_string(win_rate: float, rng: random.Random, n: int = 5) -> List[str]:
    """Generate a plausible W/D/L form list around an implied strength."""
    out: List[str] = []
    for _ in range(n):
        r = rng.random()
        if r < win_rate * 0.7:
            out.append('W')
        elif r < win_rate * 0.7 + 0.25:
            out.append('D')
        else:
            out.append('L')
    return out


def _build_match_row(lh: float, la: float, rng: random.Random,
                     odds_noise: float = 0.1, odds_missing_prob: float = 0.0
                     ) -> Dict:
    """Construct the noisy match row an engine would see for true rates.

    The row deliberately omits forebet exact score and goal averages so the
    engine must rely on its odds/form/H2H Poisson tier-3 inference — the
    realistic production case.

    Args:
        odds_noise: multiplicative jitter applied to fair probabilities
                    before converting to odds (higher = sharper market noise).
        odds_missing_prob: probability that the whole odds block is dropped,
                    simulating matches with no market data at all.
    """
    ph, pd, pa = _true_poisson_probs(lh, la)

    # Form correlated with true strength.
    home_strength = ph + pd * 0.5
    away_strength = pa + pd * 0.5
    home_form = _form_string(home_strength, rng)
    away_form = _form_string(away_strength, rng)

    row: Dict = {
        'home_team': 'H', 'away_team': 'A', 'sport': 'football',
        'home_form': home_form, 'away_form': away_form,
        'focus_team': 'home',
    }

    if rng.random() >= odds_missing_prob:
        # Bookmaker odds: fair odds blurred with noise + ~6% margin.
        margin = 1.06
        lo, hi = 1.0 - odds_noise, 1.0 + odds_noise

        def _noisy(p: float) -> float:
            p_noisy = max(0.02, min(0.95, p * rng.uniform(lo, hi)))
            return round(1.0 / (p_noisy * margin), 2)

        row['home_odds'] = _noisy(ph)
        row['draw_odds'] = _noisy(pd)
        row['away_odds'] = _noisy(pa)

    return row


def run_simulation(n_trials: int, seed: int = 42,
                   odds_noise: float = 0.1, odds_missing_prob: float = 0.0
                   ) -> Dict[str, Dict]:
    """Monte-Carlo ablation: engine with vs without the Poisson draw source."""
    rng = random.Random(seed)
    eng_on = _make_engine(with_poisson=True)
    eng_off = _make_engine(with_poisson=False)

    m_on = BacktestMetrics('with_poisson')
    m_off = BacktestMetrics('without_poisson')

    for _ in range(n_trials):
        # Draw realistic Premier-League-like goal rates.
        lh = rng.uniform(0.6, 2.6)
        la = rng.uniform(0.5, 2.2)

        score_h, score_a = _sample_score(lh, la, rng)
        if score_h > score_a:
            actual = '1'
        elif score_h == score_a:
            actual = 'X'
        else:
            actual = '2'

        row = _build_match_row(lh, la, rng,
                               odds_noise=odds_noise,
                               odds_missing_prob=odds_missing_prob)

        s_on = eng_on.score_match(row)
        s_off = eng_off.score_match(row)

        m_on.add(_probs_from_scored(s_on), actual, s_on.best_pick)
        m_off.add(_probs_from_scored(s_off), actual, s_off.best_pick)

    return {
        'with_poisson': m_on.summary(),
        'without_poisson': m_off.summary(),
        'scenario': {
            'odds_noise': odds_noise,
            'odds_missing_prob': odds_missing_prob,
        },
    }


# ---------------------------------------------------------------------------
# Real-data mode
# ---------------------------------------------------------------------------

def _load_rows(path: str) -> List[Dict]:
    if path.endswith('.csv'):
        import csv
        with open(path, 'r', encoding='utf-8-sig') as fh:
            return list(csv.DictReader(fh))
    with open(path, 'r', encoding='utf-8-sig') as fh:
        data = json.load(fh)
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        for key in ('matches', 'results', 'predictions', 'data'):
            if key in data and isinstance(data[key], list):
                return data[key]
    return []


def run_real(path: str) -> Dict[str, Dict]:
    """Backtest on rows carrying ``actual_result`` ('1'/'X'/'2')."""
    rows = _load_rows(path)
    eng = FootballScoringEngine()
    metrics = BacktestMetrics(f'real:{os.path.basename(path)}')

    # Reliability bins: does predicted probability match observed frequency?
    bins = [(0.0, 0.3), (0.3, 0.45), (0.45, 0.6), (0.6, 0.75), (0.75, 1.01)]
    bin_pred: List[float] = [0.0] * len(bins)
    bin_hit: List[float] = [0.0] * len(bins)
    bin_cnt: List[int] = [0] * len(bins)

    used = 0
    for row in rows:
        actual = str(row.get('actual_result', '')).strip().upper()
        if actual not in ('1', 'X', '2'):
            continue
        sm = eng.score_match(row)
        metrics.add(
            _probs_from_scored(sm), actual, sm.best_pick,
            ev=sm.ev, odds=sm.best_odds,
        )
        # Reliability: bucket the model's confidence in its own pick.
        p_pick = sm.best_prob
        for bi, (lo, hi) in enumerate(bins):
            if lo <= p_pick < hi:
                bin_pred[bi] += p_pick
                bin_hit[bi] += 1.0 if sm.best_pick == actual else 0.0
                bin_cnt[bi] += 1
                break
        used += 1

    if used == 0:
        print(f"[backtest] No rows with actual_result in {path}")

    reliability = []
    for bi, (lo, hi) in enumerate(bins):
        if bin_cnt[bi] > 0:
            reliability.append({
                'range': f'{lo:.2f}-{hi:.2f}',
                'n': bin_cnt[bi],
                'avg_predicted': round(bin_pred[bi] / bin_cnt[bi], 3),
                'observed': round(bin_hit[bi] / bin_cnt[bi], 3),
            })

    out = {'real': metrics.summary()}
    if reliability:
        out['reliability'] = reliability  # type: ignore[assignment]
    return out


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def _print_comparison(res: Dict[str, Dict]) -> None:
    on = res.get('with_poisson')
    off = res.get('without_poisson')
    if on and off:
        print(f"\n{'='*64}")
        print(f"  SIMULATION ABLATION — Poisson draw model  (n={on['n']})")
        print(f"{'='*64}")
        print(f"  {'metric':<14}{'without':>12}{'with':>12}{'delta':>12}")
        print(f"  {'-'*50}")
        for key, better_lower in (
            ('accuracy', False), ('brier', True),
            ('log_loss', True), ('draw_brier', True),
        ):
            o = off[key]
            n = on[key]
            delta = n - o
            arrow = ''
            if better_lower:
                arrow = '  better' if delta < 0 else ('  worse' if delta > 0 else '')
            else:
                arrow = '  better' if delta > 0 else ('  worse' if delta < 0 else '')
            print(f"  {key:<14}{o:>12.4f}{n:>12.4f}{delta:>+12.4f}{arrow}")
        print(f"\n  draws in sample: {on['draw_n']} / {on['n']} "
              f"({100*on['draw_n']/max(1,on['n']):.1f}%)")
        print(f"{'='*64}\n")
    else:
        for label, m in res.items():
            if label == 'reliability' and isinstance(m, list):
                print(f"\n[reliability]  (predicted vs observed hit-rate)")
                print(f"   {'range':<12}{'n':>6}{'predicted':>12}{'observed':>12}")
                for b in m:
                    print(f"   {b['range']:<12}{b['n']:>6}"
                          f"{b['avg_predicted']:>12.3f}{b['observed']:>12.3f}")
                continue
            if not isinstance(m, dict):
                continue
            print(f"\n[{label}]")
            for k, v in m.items():
                print(f"   {k:<14}: {v}")


def main() -> None:
    ap = argparse.ArgumentParser(description='Backtest the football scoring engine')
    ap.add_argument('--simulate', type=int, metavar='N',
                    help='Run Monte-Carlo ablation with N simulated matches')
    ap.add_argument('--seed', type=int, default=42, help='RNG seed for simulation')
    ap.add_argument('--odds-noise', type=float, default=0.1,
                    help='Market noise level (0=sharp, 0.3=loose) for simulation')
    ap.add_argument('--odds-missing', type=float, default=0.0,
                    help='Probability that a match has no odds at all (0..1)')
    ap.add_argument('--real', metavar='PATH',
                    help='Backtest on a JSON/CSV file containing actual_result')
    ap.add_argument('--json', action='store_true', help='Emit raw JSON only')
    args = ap.parse_args()

    if args.simulate:
        res = run_simulation(args.simulate, seed=args.seed,
                             odds_noise=args.odds_noise,
                             odds_missing_prob=args.odds_missing)
    elif args.real:
        res = run_real(args.real)
    else:
        ap.print_help()
        return

    if args.json:
        print(json.dumps(res, indent=2))
    else:
        _print_comparison(res)


if __name__ == '__main__':
    main()
